# Generated by Django 4.2 on 2023-07-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='categories/'),
            preserve_default=False,
        ),
    ]
