# Generated by Django 4.2 on 2023-07-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_category_pictures_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='categories/'),
        ),
    ]
